language: cpp

script:
- cd hello_world_application/
- cmake . && cmake --build . && cmake --build . --target package
- cmake . && cmake --build . && cmake --build . --target package_source
- cd ..//solver_application/
- cmake . && cmake --build . && cmake --build . --target package
- cmake . && cmake --build . && cmake --build . --target package_source
- cd .
- cpack -G DEB

addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data
      - mingw-w64
      - rpm
deploy:
  provider: releases
  api_key: 
    secure: "W+x2DpIWdDJRblpbu9q/dS/LU0nFSy9kS5P2+3uleA/dVhYofb7xqdEc7UYMD2I+jzK+9n4TXq1GzlaLw4te+d2cRWpWvVA59y09e8mwi65X7/4ofVYkcSOHBh515C3KYJ6G0q08Ig1z9laweCiJ3R83GjmFP+XGfzkKwKPtKrKS/KCeKnzMbeaQwDpUNOR667B1tp+yYGyIiUlECuDwKKac9cLpvUzwwd0AX+7yvTXmY44nyO25V0kv7WQ46m/su5YrMi5uKFd2fB1U9UFDIvuFmhX/SSfFSH03FXsCSomZLgPwu9AMcxHLnb/uxzr3UD0ShqOrhPsaCj3gHjwbtPJbk5nyZYrenr5Vb2hYIuDgvJeeTDJ6jEM9TEJKmZ5OBH63+ZG/aAt3iP55pMlU8gVi2yijQWMl84u2Wi69iFlCF2FAtKBWdoU3xS677M354UZaWTmmkUfXT2B2H6c9tGjz+12uMAIW082C48z0M4IfrYD8Pu+V1onvD9EiY2N55AuGdf4ULmKUZ4iVelDFv8WCrpON2Av6N5keYQbN/CS2l0KgdA15kRiv9lYhfdF+fFAOnkd5T9v+YdnxZw+styLbYlrjCs4rE6Z6jwqEtnTROiPbxMBymLw4kwtzplv9xtZoRFEwbFPRI7svQtWei7U2yJiofTpJ7amN0mZPcn0="
  file: "/home/travis/build/Rogopl/lab06_homework/solver_application/solver-0.1.1-Linux.deb"
  skip_cleanup: true
  on:
    branch: release
