language: cpp

script:
- cd hello_world_application/
- cmake . && cmake --build . && cmake --build . --target package
- cmake . && cmake --build . && cmake --build . --target package_source
- cd ..//solver_application/
- cmake . && cmake --build . && cmake --build . --target package
- cmake . && cmake --build . && cmake --build . --target package_source
- cd .
- cpack -G DEB

addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data
      - mingw-w64
      - rpm
deploy:
  provider: releases
  api_key: 
    secure: "P4aQdmjLMbdtVA93aTmpHOYofu/G/+q3cecJs47inscWEr2mYZRIYX+OX0bxT7TWWIT/qMPADUni85//Y60jucuAGbCT0ECbdNxwdCM3kA9HEch7MtCzsvh2xcF5VF0t9ePFg9BBAX88zwoL4z83LdV8Flep2MFZlmOHrFq9wavYAxOn/mfiWz1M7sDiujGepeb/hpE8pyW6Z6gTLyVSmsPzl2OZe0ye149fS8mbAmlSirF1TMrbDZNB6Z+wGBeRVL0ZHYILJ0m9LcdS8RUyVNwiQ8K0EvyDV64YkvtdjfWEtnVn+a/p3+TGlIzgMV4FUVJGrnHLu4rml6TwmpsfTTsO9aqu66RnFKVeFiwB5KVlXVZm/iSbzHpsoI5fkpPtsRUgVg7pZaFSiVkAPl786B2II2r3ALjJttMBCKRga3FnMSQ/mfAVHQFDk8dOf1IhTwbMpgJqVLuIBWmFuE7abdySqs5mtrgCcxYmoGZroFf1MerKqRhbFkbrZB6A73eBJf5GXjJrcFdZam+OJW8AnJT5qn8Uyb4qL8w+COs7lc59mm7YJ2cSda+Ewlgr6qeT33F8fHK8KoR2koUXpxS7RCDt8HHDd38JIHcYEyKWqGdeojI8ouAL17FkWjNPUR2mw9PBAzEZIlZs89n3/xgT182AAQKhpi5TyHVIGdeoq60=" 
  file: "/home/travis/build/Rogopl/lab06_homework/solver_application/solver-0.1.1-Linux.deb"
  skip_cleanup: true
  on:
    branch: release
